---
title: "Introduction to $\\mathtt{R}$"
subtitle: "Session 4 -- Data manipulation"
author: "Statistical Consulting Centre"
date: "19 July, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = FALSE)
# knitr::opts_chunk$set(eval = FALSE)

lake.df <- read.csv("..\\..\\data\\Lake.csv", 
                      stringsAsFactors = FALSE)

lake.df$pHtype <- with(lake.df, ifelse(pH > 7, "alkalinity", ifelse(pH < 7, "acidity", "natural")))
lake.df$pHtype <- factor(lake.df$pHtype, levels = c( "acidity", "natural", "alkalinity"))
lake.df$Calcium <- factor(lake.df$Calcium, levels = c("Low", "Medium", "High"))

mercury.df <- read.csv("..\\..\\data\\Mercury.csv", 
                      stringsAsFactors = FALSE)
library(dplyr)
joined.df <- left_join(lake.df, mercury.df, by = "ID")
```

#1. `apply()` function 

1. Check the one-way frequency tables of pHtype and Calcium.

```{r}
apply(joined.df[, c("pHtype", "Calcium")], 2, table)

```


2. Calculate the means and standard deviations of pH, Chlorophyll and mercury measuremnts at Day 1, 2, and  
```{r}
apply(joined.df[, c("pH", "Chlorophyll", "Day1", "Day2", "Day3")], 2, mean, na.rm=TRUE)

apply(joined.df[, c("pH", "Chlorophyll", "Day1", "Day2", "Day3")], 2, sd, na.rm=TRUE)

```
